`osmborder` support for openstreetmap.fr extracts (#216)
openstreetmap.fr tends to generate extracts with the non-existing refs, and needs to be cleaned up. This patch uses `osmconvert --drop-broken-refs ...` on the PBF file before generating borders file.

The feature is disabled by default. Enable it by setting `BORDERS_CLEANUP=true`

Resolve #215

Co-authored-by: Yuri Astrakhan <YuriAstrakhan@gmail.com>

diff --git a/bin/import-borders b/bin/import-borders
--- a/bin/import-borders
+++ b/bin/import-borders
@@ -4,7 +4,8 @@ set -o pipefail
 set -o nounset
 
 : "${PBF_DATA_DIR:=/import}"
-# Do not use .pbf extension to avoid accidental conflict with the original pbf with multiple runs
+: "${BORDERS_CLEANUP:=false}"
+: "${BORDERS_CLEANUP_FILE:="$PBF_DATA_DIR/borders/cleanup.pbf"}"
 : "${BORDERS_PBF_FILE:="$PBF_DATA_DIR/borders/filtered.pbf"}"
 : "${BORDERS_CSV_FILE:="$PBF_DATA_DIR/borders/lines.csv"}"
 : "${BORDERS_TABLE_NAME:=osm_border_linestring}"
@@ -17,8 +18,9 @@ function usage() {
   >&2 echo "import-borders parse planet.pbf     - Parse planet.pbf into a CSV file, but do not import"
   >&2 echo "import-borders load borders.csv     - Load borders.csv into a table"
   >&2 echo ""
-  >&2 echo "Expected variables:  PGHOST, PGDATABASE, PGUSER, PGPASSWORD"
-  >&2 echo "Supported variables:  PBF_DATA_DIR, BORDERS_PBF_FILE, BORDERS_CSV_FILE, BORDERS_TABLE_NAME, PGPORT"
+  >&2 echo "Expected variables:   PGHOST, PGDATABASE, PGUSER, PGPASSWORD"
+  >&2 echo "Supported variables:  PBF_DATA_DIR, BORDERS_PBF_FILE, BORDERS_CSV_FILE, BORDERS_TABLE_NAME, PGPORT,"
+  >&2 echo "                      BORDERS_CLEANUP, BORDERS_CLEANUP_FILE"
   >&2 echo ""
   >&2 echo "If first parameter is a file, treat it as 'import'"
   >&2 echo ""
@@ -57,6 +59,20 @@ task="$1"
 if [[ "$task" == "import" || "$task" == "parse" ]]; then
   # Parse PBF file to generate borders CSV file, and import it into PG
   IMPORT_PBF_FILE="$2"
+
+  if [[ "$BORDERS_CLEANUP" == "true" ]]; then
+    # Some OSM extracts may include references to elements that are not included in the extract
+    echo "Cleaning-up broken references from $IMPORT_PBF_FILE into $BORDERS_CLEANUP_FILE"
+    echo "Set BORDERS_CLEANUP=false to skip the cleanup -- it is not needed for the full planet and Geofabrik downloads"
+    mkdir -p "$(dirname "${BORDERS_CLEANUP_FILE:?}")"
+    rm -rf "$BORDERS_CLEANUP_FILE"
+    osmconvert --drop-broken-refs -b=-180,-90,180,90 --out-pbf -o="$BORDERS_CLEANUP_FILE" "$IMPORT_PBF_FILE"
+    IMPORT_PBF_FILE="$BORDERS_CLEANUP_FILE"
+  else
+    echo "Skipping broken references cleanup because BORDERS_CLEANUP is not set to 'true'"
+    echo "Enable borders cleanup if you see 'location for one or more nodes not found in node location index' error"
+  fi
+
   echo "Filtering $IMPORT_PBF_FILE into $BORDERS_PBF_FILE"
   mkdir -p "$(dirname "${BORDERS_PBF_FILE:?}")"
   rm -rf "$BORDERS_PBF_FILE"
